completed validations extension
ppauljonathan/rails-depot-app pull request #4
Opened 2023-04-05 13:27 UTC by ppauljonathan

# Extensions question

## Validations

### In product model add validations for following
1) Permalink
- should be unique
- no special character and no space allowed
- minimum 3 words, separated by hyphen 
2) Price numericality validation should only run if price is present.
3) Description - should be between 5 and 10 words
4) Validate image_url format by using url:true(ActiveModel::EachValidator)
5) In product model, price should be greater than discount price
- using custom validator
- without custom validator

### LineItems model
1) Combination of product_id and cart_id should be unique. Means one product can be added only once in the cart. If cart with cart_id exists.

### Add following validations in user model
1) Uniqueness of email
2) Email format

2023-04-10 12:42 UTC, shubhamjuneja1 requested changes
Answer all ques as discussed

2023-04-10 12:48 UTC, shubhamjuneja1 requested changes

2023-04-10 12:48 UTC, shubhamjuneja1 commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: { scope: :cart_id, message: 'should be given only once in cart' }
check if we can pass array?

2023-04-10 12:48 UTC, shubhamjuneja1 commented on app/models/product.rb
> +    return unless value =~ PERMITTED_IMAGE_URL_TYPES_REGEX
fix

2023-04-10 12:48 UTC, shubhamjuneja1 commented on app/models/product.rb
> +      permalink&.split('-')
& -> is required here?

2023-04-10 12:48 UTC, shubhamjuneja1 commented on app/models/product.rb
> +  validate :price_greater_than_discount_price
can we use if,else or anything else here?

2023-04-10 12:48 UTC, shubhamjuneja1 commented on config/initializers/constants.rb
> +PERMITTED_IMAGE_URL_TYPES_REGEX = /\.(gif|jpg|png)\z/i.freeze
try to find the reason for this

2023-04-10 13:39 UTC, ppauljonathan commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: { scope: :cart_id, message: 'should be given only once in cart' }
yes we can pass array like `uniqueness: { scope: [:cart_id :date] }

2023-04-11 07:09 UTC, ppauljonathan commented on config/initializers/constants.rb
> +PERMITTED_IMAGE_URL_TYPES_REGEX = /\.(gif|jpg|png)\z/i.freeze
at the time there was a problem with the rails console since i had already defined the constants in the irb session

2023-04-11 07:09 UTC, ppauljonathan commented on config/initializers/constants.rb
> +PERMITTED_IMAGE_URL_TYPES_REGEX = /\.(gif|jpg|png)\z/i.freeze
moved constants back to their respective places

2023-04-11 07:12 UTC, ppauljonathan commented on app/models/product.rb
> +  validate :price_greater_than_discount_price
yes we can use `:if`, `:unless`, and `:on` here, moved the conditions in the function to the `if:` option

2023-04-13 09:58 UTC, shubhamjuneja1 commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: { scope: :cart_id, message: 'should be given only once in cart' }
check if cart is loaded if cart is used instead of cart_id

2023-04-14 06:03 UTC, ppauljonathan commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: { scope: :cart_id, message: 'should be given only once in cart' }
yes the cart is loaded since in the `LineItem` object there are two methods `cart` and `cart=` which are created by the `belongs_to` method, `cart` returns the associated cart and `cart=` assigns an object of `Cart` to the `LineItem`, and also when we look in the console we can see that it is running an SQL query to select the cart

2023-04-17 19:22 UTC, shubhamjuneja1 approved these changes

2023-04-18 04:46 UTC, merged