completed callbacks extension
ppauljonathan/rails-depot-app pull request #5
Opened 2023-04-10 06:44 UTC by ppauljonathan

## Callbacks
- Product should be always be initialized with default title 'abc' if no title given.
- Discount price should be equal to price unless specified explicitly.
- Send a mail with subject 'Welcome' on users mail after new user is created.
- User should not be destroyed if email is 'admin@depot.com'
- Should not be able to update user if email is '[admin@depot.com](mailto:admin@depot.com)'

2023-04-10 13:00 UTC, shubhamjuneja1 commented on app/models/user.rb
> +      return unless user.is_admin?
remove this and make it normal callbacks

2023-04-11 12:00 UTC, ppauljonathan commented on app/models/product.rb
> +  before_validation :assign_default_title, :assign_default_discount_price
we cannot use `before_save` as during `save()` method, the validations are called and the `before_save` hook is never called until all the validations pass, same with the `after_validation` hook

2023-04-11 13:08 UTC, ppauljonathan commented on app/mailers/user_mailer.rb
> +  default from: 'Paul <depot@example.com>'
done

2023-04-11 13:08 UTC, ppauljonathan commented on app/models/product.rb
> +    def assign_default_discount_price
done

2023-04-11 13:09 UTC, ppauljonathan commented on app/controllers/users_controller.rb
> +        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
used I18n in all of users resource files

2023-04-11 13:09 UTC, ppauljonathan commented on app/models/product.rb
> +      return unless title.blank?
done and added `if:` and `unless:` options

2023-04-11 13:10 UTC, ppauljonathan commented on app/models/user.rb
> +      return unless user.is_admin?
removed `AdminCallbacks`

2023-04-11 13:10 UTC, ppauljonathan commented on app/mailers/user_mailer.rb
> +    mail to: user.email, subject: 'Welcome'
done, also added i18n

2023-04-13 10:13 UTC, shubhamjuneja1 requested changes

2023-04-13 10:13 UTC, shubhamjuneja1 commented on app/mailers/user_mailer.rb
> +    @user = User.find(user_id)
return unless @user

2023-04-13 10:13 UTC, shubhamjuneja1 commented on app/models/product.rb
> +      self.title = 'abc'
constant

2023-04-13 10:13 UTC, shubhamjuneja1 commented on app/models/user.rb
> +      raise Error, "Can't update/delete admin"
what if we have used throw :abort

2023-04-13 10:13 UTC, shubhamjuneja1 commented on app/models/user.rb
> +  class Error < StandardError
it can be extracted

2023-04-14 07:26 UTC, ppauljonathan commented on app/mailers/user_mailer.rb
> +    @user = User.find(user_id)
done

2023-04-14 07:27 UTC, ppauljonathan commented on app/models/product.rb
> +      self.title = 'abc'
done

2023-04-14 07:29 UTC, ppauljonathan commented on app/models/user.rb
> +  class Error < StandardError
extracted to `app/models/concerns/last_user_delete_error.rb`

2023-04-14 07:31 UTC, ppauljonathan commented on app/models/user.rb
> +      raise Error, "Can't update/delete admin"
when we use `throw :abort` the execution chain stops and a `ROLLBACK` is issued, we can then handle the case in the controllers where `@user.save` fails and render the page with an error on the top

2023-04-14 07:53 UTC, ppauljonathan commented on app/models/user.rb
> +      UserMailer.registered(self).deliver_later
> check how this working?

this happens because the `ActionMailer::Base` class (which `UserMailer` inherits from)

When we define instance methods in the `UserMailer` Class they are added to an `@action_methods` instance variable which belongs to `AbstractController::Base` which is the superclass of `ActionMailer::Base`, inside `ActionMailer::Base` there is a `self.method_missing` which checks if the method passed to it is included in `@action_methods`, if no then it throws a `NoMethodError`, if yes then it returns `ActionMailer::MessageDelivery` object, the instance of `ActionMailer::MessageDelivery` contains methods like `deliver_now` and `deliver_later`, which are used to deliver the mail

2023-04-17 19:20 UTC, shubhamjuneja1 commented on app/models/user.rb
> +        raise LastUserDeleteError, "Can't Delete Last User"
it should not be specific to last user delete error
but something related to user deletion

2023-04-17 19:20 UTC, shubhamjuneja1 approved these changes

2023-04-18 04:50 UTC, ppauljonathan commented on app/models/user.rb
> +        raise LastUserDeleteError, "Can't Delete Last User"
renamed to `UserDeleteError`

2023-04-18 04:56 UTC, merged